### ISSUE TITLE
shared cert seemingly removed

### ISSUE THREAD

**Issue by vdice** [deis/router#142]
Consider the following scenario:
```
two domains are added to an app, domainA and domainB
a previously added cert is attached to both domains
the cert is detached from only domainA
```

This scenario, in the form of the e2e test seen [here](https://github.com/vdice/workflow-e2e/blob/revisit-certs-test/tests/certs_test.go#L301-L340), leads to the cert seemingly also detached from the other domainB (or perhaps the cert is removed altogether) even though `certs:info` shows the attachment to domainB still exists.  

The current behavior after the steps above is a `404` is returned when `curl`ing domainB's SSL endpoint, whereas one would expect a `200` still be returned - as is the case when both domains are still attached to the cert.

See https://github.com/deis/workflow/pull/492 for related scenario/logic.

**Comment by krancour** [comment]
@vdice nice catch.  I've put this to the test and have been able to reproduce... however, I believe this is actually a controller bug.

> two domains are added to an app, domainA and domainB
a previously added cert is attached to both domains

Manually putting this to the test, at this stage, the service for such an application contains the following relevant annotations:

```
metadata:
  annotations:
    router.deis.io/certificates: domain-a.foo.com:foo-wildcard,domain-b.foo.com:foo-wildcard
    router.deis.io/domains: timely-odometer,domain-a.foo.com,domain-b.foo.com
```

And the certificate in question is visible in the app's namespace:

```
$ kubectl get secrets --namespace=timely-odometer
NAME                  TYPE                                  DATA      AGE
default-token-ja4wo   kubernetes.io/service-account-token   2         53m
foo-wildcard-cert     Opaque                                2         21s
minio-user            Opaque  
```

After detachment of the `foo-wildcard` certificate from `domain-b.foo.com`, the annotations on the service appear _correct_.

```
metadata:
  annotations:
    router.deis.io/certificates: domain-b.foo.com:foo-wildcard
    router.deis.io/domains: timely-odometer,domain-a.foo.com,domain-b.foo.com
```

The problem, however, is that the secret that contains the cert has disappeared:

```
$ kubectl get secrets --namespace=timely-odometer
NAME                  TYPE                                  DATA      AGE
default-token-ja4wo   kubernetes.io/service-account-token   2         58m
minio-user            Opaque                                2         58m
```

I would theorize that in the controller, the detachment is removing the secret from the namespace without regard for whether the cert container within might also be attached to _other_ domains of the same app (therefore in the same namespace).

I will open a separate issue against the controller and reference this one.  This issue has also brought to light that the router isn't logging any sort of warning when a secret containing a cert that is expected to exist is not found.  I will close this and open a separate issue for that.
