### ISSUE TITLE
HTTPS is not being enforced

### ISSUE THREAD

**Issue by pixeleet** [deis/router#243]
Hey Guys, Why could it be the HTTPS is not enforced on the domains even though I have enabled it.
I have a `platformDomain` and a `deis-router-platform-cert` set up. 
All domains have individual certificates attached to them too with `deis certs:attach <cert> <domain>` 

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deis-router
  namespace: deis
  labels:
    heritage: deis
  annotations:
    helm-keep: "true"
    router.deis.io/nginx.ssl.enforce: "true"
    router.deis.io/nginx.ssl.hsts.enabled: "true"
    router.deis.io/nginx.platformDomain: “mydomain.com"
```
