### ISSUE TITLE
"client intended to send too large body" event after setting bodySize annotation

### ISSUE THREAD

**Issue by olalonde** [deis/router#245]
I added the following annotation to deis-router:

```yaml
apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    chart.helm.sh/description: Deis Workflow
    chart.helm.sh/file: /Users/olalonde/.helmc/workspace/charts/workflow-v2.4.1/manifests/deis-router-rc.yaml
    chart.helm.sh/name: workflow-v2.4.1
    chart.helm.sh/version: v2.4.1
    component.deis.io/version: v2.4.0
    router.deis.io/nginx.bodySize: 500M
```

However, even after making sure the annotation is set correctly with `kd edit rc deis-router` and killing the deis router pod `kd delete po deis-router-2319742441-rjpcf`, I'm still getting "413 entitity too large" NGINX responses when uploading a 1.8MB file to my server:

```
2016/09/02 23:03:21 [error] 171#0: *3609565 client intended to send too large body: 1817648 bytes, client: 184.23.11.102, server: domain.com, request: "POST /api/v1/registrations HTTP/1.1", host: "domain.com", referrer: "https://domain.com/"
````
