### ISSUE TITLE
Make workflow ingress compatible

### ISSUE THREAD

**Issue by rothgar** [deis/router#292]
With an on-prem installation I don't have external load balancers and rely on ingress controllers for service routing. The problems with the existing router solution are

- Not all of my services will be deployed/managed with deis router so I need to use an ingress controller for those services
- To load balance my ingress controller I run it as a daemonset on all workers which means the deis router is unable to deploy pods due to port conflicts (ports 80 and 443)
- If I'm not using the deis router then workflow deployed services won't automatically be routed because they rely on service annotations instead of ingress rules

It may be possible to deploy the router on alternative ports which might satisfy needs temporarily but it would be nice if all services were routed via ingress rules in the api server instead of needing to look multiple places for hostname/service routing.

I'm attempting to make some of the rules needed but running into problems. Mainly the ingress controller shows no backend service IPs for the below ingress rule (I figure figured out why yet)

```yaml
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: deis-controller
  namespace: deis
spec:
  rules:
  - host: deis-controller
    http:
      paths:
      - backend:
          serviceName: deis-controller
          servicePort: http
```

As far as I could find I would need to make ingress rules for the controller (80, 443), builder (2222), and workflow-manager (80). There are others that are exposed with router.deis.io/routable="true" such as deis-monitor-grafana, deis-monitor-influxapi, and deis-monitor-influxui but these don't see as necessary to have externally exposed.
